"""Module for Exceptions classes"""

from enum import Enum


# Class contains define error_type
class ErrorType(str, Enum):
    NOT_FOUND = "not_found"
    VALIDATION = "validation_error"
    CONFLICT = "conflict"
    UNAUTHORIZED = "unauthorized"
    FORBIDDEN = "forbidden"
    EXTERNAL_SERVICE = "external_service_error"
    INTERNAL = "internal_error"
    INVALID = "invalid_error"


class AppException(Exception):
    """Base App exception for all application exception"""

    error_type: ErrorType = ErrorType.INTERNAL

    def __init__(self, message: str, *, details: dict | None = None):
        self.message = message
        self.details = details or {}
        super().__init__(message)


class LLMServieException(AppException):
    """LLMServieException class for llm services like client failed to generate"""

    error_type = ErrorType.EXTERNAL_SERVICE

    def __init__(
        self, message: str = "llm_client failed to generate response", *, details=None
    ):
        super().__init__(message, details=details)


class UnSupportedResource(AppException):
    """Exception for resources which are unsupported by our application"""

    error_type = ErrorType.VALIDATION

    def __init__(
        self,
        message: str = "Invalid or Unsupported Resources are provided",
        *,
        details: dict | None = None,
    ):
        super().__init__(message, details=details)


class ValidationException(AppException):
    """Exception for validation error where user provided invalid values."""

    error_type = ErrorType.VALIDATION

    def __init__(self, message: str = "InValid values are provided", *, details=None):
        super().__init__(message, details=details)


class DuplicateResourceException(AppException):
    """Exception for resources which are already exist"""

    error_type = ErrorType.CONFLICT

    def __init__(
        self,
        message: str = "resource already exist",
        details: dict | None = None,
    ):
        super().__init__(
            message,
            details=details,
        )


# we need to change this class into an exception rather than appexcetpion because filepaths are generated by ours not user so that if error gets there is our code mistakes
class InvalidFilePaths(AppException):
    """Exception for invalid files path"""

    error_type = ErrorType.INTERNAL

    def __init__(self, message, *, details: dict | None = None):
        super().__init__(message, details=details)


class ResourceNotFoundException(AppException):
    """Exception for resource not found"""

    error_type = ErrorType.NOT_FOUND

    def __init__(
        self,
        message: str = "resource not found",
        *,
        details: dict | None = None,
    ):
        super().__init__(
            message,
            details=details,
        )


class InvalidCredentialsException(AppException):
    """Exception for Invalid Credentials."""

    error_type = ErrorType.UNAUTHORIZED

    def __init__(
        self, message: str = "Invalid Credentials", *, details: dict | None = None
    ):
        super().__init__(message, details=details)
